In [7]:

import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [8]:
a=[1,2,3,4,5,'hello','python']
a

[1, 2, 3, 4, 5, 'hello', 'python']

In [9]:
np.array([1,3,6,7,9,8,6,'numpy'])

np.array([1,3,4,1.5,57])

array([ 1. ,  3. ,  4. ,  1.5, 57. ])

In [15]:
np.array([1,2,3,4,'hello','python full stack ','uvesh'])

array(['1', '2', '3', '4', 'hello', 'python full stack ', 'uvesh'],
      dtype='<U21')

In [20]:
l=[[1,2,3],[4,5,6],[8,9,10]]
l

[[1, 2, 3], [4, 5, 6], [8, 9, 10]]

In [21]:
np.array(l)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [27]:
# # np.arange(1,10,2)

# arr=np.zeros(6)
# arr



arr=np.zeros((4,8))
arr



array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
# arr=np.ones((6,6))
# arr
arr=np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# linspace are the same space in array element
#normalization 0 middle value 1 
#standard divison -3 to 3

arr=np.linspace(1,5,4)
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [36]:
np.random.rand(5)

array([0.00823121, 0.58947858, 0.6465102 , 0.81068643, 0.63682271])

In [37]:
np.random.randn(10)

array([-0.08877669,  2.58723691,  0.01169686,  0.37759524,  0.6224854 ,
        0.25558031,  0.31440644, -0.06813762, -2.21132944, -0.62468321])

In [10]:
np.random.randint(10,20,10)

array([11, 10, 17, 12, 19, 11, 10, 17, 13, 10], dtype=int32)

In [11]:
ar=np.array([[1,2,3],[4,7,9],[78,34,67]])
ar
ar.shape
ar.size
ar.dtype

dtype('int64')

In [29]:

# ar.min()
# ar.max()
ar.sum()



np.int64(205)

In [14]:
ar


array([[ 1,  2,  3],
       [ 4,  7,  9],
       [78, 34, 67]])

In [ ]:
np.sum(ar,axis=0)


array([83, 43, 79])

In [26]:
ar.mean()


np.float64(22.77777777777778)

In [27]:
ar.std()

np.float64(28.322655940186344)

In [32]:
# ar.argmin()
ar.argmax()

np.int64(6)

In [35]:
ara=np.arange(12,50)

ara

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49])

In [36]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [45]:
arr[2:7]

array([13, 14, 15, 16, 17])

In [47]:
arr[1:5]

array([12, 13, 14, 15])

In [49]:
arr[1::2]

array([12, 14, 16, 18, 20])

In [50]:
arr=np.arange(1,31).reshape(6,5)

In [53]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [55]:
np.sum(arr,axis=0)

array([ 81,  87,  93,  99, 105])

In [56]:
arr[5]

array([26, 27, 28, 29, 30])

In [63]:
# arr[0,0]

#arr[0,4]

# arr[1,4]

arr[3,1]


np.int64(17)

In [66]:
a=np.arange(11,21)

In [67]:
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [68]:
index=a%2==0
index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [70]:
arr=a[index]
arr

array([12, 14, 16, 18, 20])

In [72]:
p=np.arange(30,50)
p

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [73]:
a=p%2==0
a

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [74]:
b=p[a]
b

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [76]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a1
a2

array([ 6,  7,  8,  9, 10])

In [77]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [79]:
a1*a2
a1-a2

array([-5, -5, -5, -5, -5])

In [83]:
l=[10,20,30,40]
arr=np.array(l)
for i in l:
    print(i+10)
    

20
30
40
50


In [ ]:
# arr
arr+10

array([20, 30, 40, 50])

In [91]:
arr2=np.arange(1,31).reshape(5,6)

In [92]:
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [93]:
arr2+10

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40]])

In [3]:
import numpy as np
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [4]:
a[:5]

array([1, 2, 3, 4, 5])

In [6]:
a[4:7]*10

array([50, 60, 70])

In [7]:
b=a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [9]:
b[0]=90

In [10]:
b

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
a

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])


In [23]:
a.T

array([[1, 3],
       [2, 4]])

In [24]:
b.T

array([[5, 7],
       [6, 8]])

In [38]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [5, 6],
       [7, 8]])

In [39]:
b

array([[5, 6],
       [7, 8]])

In [29]:
a@b

array([[19, 22],
       [43, 50]])

In [35]:
np.vstack((a,b))


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [5, 6],
       [7, 8],
       [5, 6],
       [7, 8]])

In [40]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [41]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]